[device]
wifi.scan-rand-mac-address=yes

[connection]
ethernet.cloned-mac-address=random
wifi.cloned-mac-address=random
connection.stable-id=${CONNECTION}/${BOOT}

[connectivity]
uri=https://nmcheck.gnome.org/check_network_status.txt
interval=0
