---
mountOptions:
  default: defaults,noatime
  btrfs: defaults,noatime,compress=zstd:3
  btrfs_swap: defaults,noatime
ssdExtraMountOptions:
  ext4: discard
  jfs: discard
  xfs: discard
  swap: discard
  btrfs: discard=async
crypttabOptions: luks,keyscript=/bin/cat
efiMountOptions: umask=0077
