---
backend: pacman
skip_if_no_internet: false
update_db: false
update_system: false
pacman:
  num_retries: 0
  disable_download_timeout: false
  needed_only: true
operations:
  - try_remove:
    - edex-os-live
    - edex-os-calamares-config
    - cachyos-calamares
    - mkinitcpio-archiso
