---
efiSystemPartition: "/boot/efi"
efiSystemPartitionSize: "512MiB"
efiSystemPartitionName: "EFI"
userSwapChoices:
  - none
  - small
  - suspend
  - file
luksGeneration: luks2
allowManualPartitioning: true
initialPartitioningChoice: erase
initialSwapChoice: small
defaultFileSystemType: "btrfs"
defaultPartitionTableType: "gpt"
availableFileSystemTypes: ["btrfs", "ext4", "xfs", "f2fs"]
drawNestedPartitions: false
alwaysShowPartitionLabels: true
enableLuksAutomatedPartitioning: true
