[Service]
ExecStart=
ExecStart=/usr/bin/nft -f /etc/edex-os/nftables.conf
ExecReload=/usr/bin/nft -f /etc/edex-os/nftables.conf
ExecStop=-/usr/bin/nft delete table inet edex-filter
RemainAfterExit=yes
