[Service]
ExecStartPre=
ExecStartPre=/usr/bin/tor -f /etc/edex-os/torrc --verify-config
ExecStart=
ExecStart=/usr/bin/tor -f /etc/edex-os/torrc
RuntimeDirectory=tor
RuntimeDirectoryMode=0750
ReadWriteDirectories=-/run/tor
