# Live medium user (created by systemd-sysusers at boot; edex-setup-live clears its password).
u liveuser 1000:1000 "eDEX Live User" /home/liveuser /usr/bin/fish
m liveuser wheel
m liveuser adm
m liveuser audio
m liveuser video
m liveuser input
m liveuser storage
m liveuser network
m liveuser rfkill
m liveuser users
m liveuser tor
