---
efiBootLoader: "grub"
kernelLine: " quiet splash loglevel=3 rd.udev.log_priority=3"
fallbackKernelLine: " loglevel=3"
timeout: 5
grubInstall: "grub-install"
grubMkconfig: "grub-mkconfig"
grubCfg: "/boot/grub/grub.cfg"
grubFallback: false
installEFIFallback: false
