---
services:
  - name: NetworkManager
    mandatory: true
  - name: bluetooth
    mandatory: false
  - name: tailscaled
    mandatory: true
  - name: dnscrypt-proxy
    mandatory: true
  - name: nftables
    mandatory: true
  - name: fprintd
    mandatory: false
  - name: seatd
    mandatory: true
  - name: fstrim.timer
    mandatory: false

targets:
  - name: graphical
    mandatory: true
