---
modules-search: [ local, /usr/lib/calamares/modules ]

sequence:
  - show:
    - welcome
    - locale
    - keyboard
    - partition
    - users
    - summary
  - exec:
    - partition
    - mount
    - unpackfs
    - machineid
    - fstab
    - locale
    - keyboard
    - localecfg
    - luksopenswaphookcfg
    - luksbootkeyfile
    - initcpiocfg
    - initcpio
    - users
    - networkcfg
    - hwclock
    - services-systemd
    - packages
    - grubcfg
    - bootloader
    - shellprocess@edex-postinstall
    - umount
  - show:
    - finished

branding: edex-os
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
