# eDEX-OS runtime and state files
d /var/lib/edex-os 0755 root root -
L+ /etc/resolv.conf - - - - /etc/edex-os/resolv.conf
f /run/edex-tor-mode 0644 root root - off\n
d /etc/tor/torrc.d 0750 root tor -
